### ISSUE TITLE
Add FAQ to site

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/gamification#26]
Containing at least:
1. Why do my bounty points degenerate?
2. Does the samen happen with my reward points?! D:

**Comment by Silox** [comment]
3. Why didn't I get my bountypoints?

> Because you weren't assigned

**Comment by Iasoon** [comment]
Do you think a FAQ would be superior to a 'How it works' section?

**Comment by Silox** [comment]
Yes


On 22 Mar 2015 at 15:35:57, Iasoon (notifications@github.com) wrote:

Do you think a FAQ would be superior to a 'How it works' section?

**Comment by Silox** [comment]
To elaborate; people are lazy. They’ll read a FAQ faster when something is wrong than a more lengthy information page.


On 22 Mar 2015 at 15:36:23, Tom Naessens (tom.naessens@ugent.be) wrote:

Yes


On 22 Mar 2015 at 15:35:57, Iasoon (notifications@github.com) wrote:

Do you think a FAQ would be superior to a 'How it works' section?
