### ISSUE TITLE
I am Caylo

### ISSUE THREAD

**Issue by becousae** [ZeusWPI/gamification#29]
![screen shot 2015-04-03 at 17 41 15](https://cloud.githubusercontent.com/assets/7578716/6984397/b7d16cda-da28-11e4-8c54-a4560cb2a1b7.png)

**Comment by Iasoon** [comment]
This isn't a gamification issue, as it also occurs on Slack. Please double check your identity.

**Comment by Iasoon** [comment]
Since you are oshab now, I'm assuming this is no longer an issue.
