### ISSUE TITLE
Hide overflowing names in top4 bar charts

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/gamification#36]
To give an example:
![screen shot 2015-07-11 at 20 52 02](https://cloud.githubusercontent.com/assets/915130/8634944/be2e3c8c-280e-11e5-9abf-60519db01313.png)

If my contribution would have been bigger, and Felix' would have been smaller, our names would overlap completely (happened before but stats have changed) so it would not be easy to see who made the biggest contribution.

**Comment by Silox** [comment]
Hmh, or not as this hides Felix' name from the barchart. We could stick to this order, but then add some padding or hide the names that have too less space and only show them when hovering while hiding the other names?

**Comment by iasoon** [comment]
I was planning to do the hiding, but did not come to finish it yet.
