### ISSUE TITLE
Post new bounties to Slack

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/gamification#37]

**Comment by Silox** [comment]
This could also be sent to Github as a mention on the specific issue, so people who don't follow Slack can also see it. This will automaticly post the comment to Slack as well with our Github integraitons.

**Comment by Procrat** [comment]
That's an interesting thought. Wouldn't that be a bit of clutter on here though?

**Comment by iasoon** [comment]
We could add a footer about the posted bounties to the issue text, and possibly edit the issue title and add a label as well, analogous to BountySource.

On the other hand, I think I would like to keep these separated myself, and instead improve the issue discovery methods included in Gamification.

**Comment by Procrat** [comment]
+1 on a footer in the issue text. Maybe a badge like this?

![Gamification bounties: 216](https://img.shields.io/badge/bounties-216-green.svg)

**Comment by Silox** [comment]
That's one neat badge :)

**Comment by Silox** [comment]
Closed in the PR
