### ISSUE TITLE
46 + 100 = 262

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/gamification#38]

**Comment by Procrat** [comment]
I don't think this is a bug. Your thoughts, @iasoon?

**Comment by Silox** [comment]
Even if it isn't a bug, it's very unintuitive for a user not knowing about the inflation. In any way, this should be made clear to the user putting the bounty. Maybe we could use a [popover](http://getbootstrap.com/javascript/#tooltips) on the updated bounty with explanations? Something like "[50 (original) + 100 (points put)] * 1.04 (inflation factor)" ?

**Comment by iasoon** [comment]
Inflation occurs when the amount of currency increases, and thus the value decreases.

Hence, this should not happen.

**Comment by Procrat** [comment]
Fixed ^
