### ISSUE TITLE
Claiming self bountied bounties

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/gamification#40]
Lets say I have 100 bounty points. I assign them all to 1 issue, having 0 points, which ends up as 150 points as inflation. If I close this issue, I obtain 150 bounty points. This seems like a way to earn bounty points very fast and can be abused.

**Comment by bmesuere** [comment]
Disable bounty earning for self-set bounties?

**Comment by iasoon** [comment]
This is not how inflation works.

**Comment by Procrat** [comment]
Will be fixed when #38 gets fixed
