### ISSUE TITLE
Check for changed access token

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/gamification#46]
When the access token changes, the remotes of the cloned repos should be changed as well

**Comment by FlashYoshi** [comment]
When github asks for a password, indicating that the access token changed, we should abort the request and just execute a substitution, substituting the old token with the new one, on the .gitconfig's of all our local repositories.

**Comment by Procrat** [comment]
I already fixed this in a1251abf4dae4c12cc13210fbc6af17771aeca05
