### ISSUE TITLE
Sorting is not intuitive

### ISSUE THREAD

**Issue by FlashYoshi** [ZeusWPI/gamification#49]
The headers don't show anything to indicate that we can sort on them.
When you sort on a different header the ranking numbers are also sorted which shouldn't happen.

**Comment by Procrat** [comment]
We're somehow currently using two different jQuery plugins for table sorting. Getting this out of the way first.

**Comment by Procrat** [comment]
@FlashYoshi: Can you confirm that it is now to your liking?

**Comment by Silox** [comment]
I like it!

**Comment by FlashYoshi** [comment]
Much better :)
