### ISSUE TITLE
when placing a bounty, make a comment on the issue

### ISSUE THREAD

**Issue by Iepoev** [ZeusWPI/gamification#59]
After placing a bounty on an issue, some sort of bot should comment on this issue with information about the bounty ( was it a pre-existing bounty, who placed it, how many points were added,..)

as an added bonus the slack github integration will also post these bounties directly in the relevant chat channels

**Comment by Silox** [comment]
Duplicate of https://github.com/ZeusWPI/gamification/issues/37
