### ISSUE TITLE
Webhook links don't include the subdirectory prefix

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/gamification#60]
Links do not include the url prefix. For example the link is: https://zeus.ugent.be/coders/feliciaan instead of https://zeus.ugent.be/game/coders/feliciaan

**Comment by Silox** [comment]
http://edgeguides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root should fix it.

**Comment by Silox** [comment]
This is an issue with Rails < 4.2 and will be fixed automaticly when Datenfisch is compatible with Rails 4.2. (Paging @iasoon)
