### ISSUE TITLE
Take name changes of repositories into account

### ISSUE THREAD

**Issue by Donvittorio** [ZeusWPI/gamification#62]
![LanApp/Lana](http://puu.sh/jO71m/875f3dc8fd.png)
Repositories such as LanApp do not get renamed. ![doggie](http://puu.sh/jO7gI/b187b7faa5.png)

**Comment by Silox** [comment]
I don't think this is possible as there is no webhook for this in https://developer.github.com/v3/activity/events/types/. Please reopen if I looked over it.
