### ISSUE TITLE
I don't even know a title for this.

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/gamification#63]
I only pushed 3-4 lines today and my points have risen from 420 to somewhere in the 900's. The currect barplot looks like this (I made the box bigger):

![screen shot 2015-08-25 at 18 51 24](https://cloud.githubusercontent.com/assets/915130/9473306/75e744cc-4b5a-11e5-9f50-5e3e45bec333.png)

**Comment by iasoon** [comment]
So in short, everything is broken?

**Comment by Procrat** [comment]
The contributor rectangle heights are based on the contributor scores, which are calculated as the score of commits + bounty scores, while the repository rectangle heights are based on the repository scores, which don't take bounty scores into account.

Fixing this.
